version: "3.9"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: conduit_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    extra_hosts:
      host.docker.internal: host-gateway

  grafana:
    build: './grafana'
    container_name: conduit_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    build:
      context: grafana
    expose:
      - 3000
    ports:
      - 9091:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
