{
 "title": "Conduit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per endpoint in selected time range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_requests_received_total[$__range])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Request durations",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_request_duration_histogram_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pipeline durations",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(conduit_pipeline_execution_duration_seconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "msg/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(conduit_pipeline_execution_duration_seconds_count[$__rate_interval])"
    }
   ]
  }
 ]
}