{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "heap inuse" }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes[$interval])",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes[$interval])",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes[$interval])",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}