{
 "title": "Performance benchmark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PipelineRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(conduit_pipeline_execution_duration_seconds_count{pipeline_name=\"perf-test\"} - \nconduit_pipeline_execution_duration_seconds_count{pipeline_name=\"perf-test\"} offset 1m) / (conduit_pipeline_execution_duration_seconds_sum{pipeline_name=\"perf-test\"} - \nconduit_pipeline_execution_duration_seconds_sum{pipeline_name=\"perf-test\"} offset 1m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RecordCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "conduit_pipeline_execution_duration_seconds_count{pipeline_name=\"perf-test\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InternalMsPerRec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(conduit_pipeline_execution_duration_seconds_sum{pipeline_name=\"perf-test\"} / conduit_pipeline_execution_duration_seconds_count{pipeline_name=\"perf-test\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InternalRecordsPerSec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "conduit_pipeline_execution_duration_seconds_count{pipeline_name=\"perf-test\"} / conduit_pipeline_execution_duration_seconds_sum{pipeline_name=\"perf-test\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}